language: c

install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.6.16/terraform_0.6.16_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

script:
  - for f in $(find . -name main.tf | grep -v .terraform); do terraform validate `dirname $f`; done
